<?php 
    require_once("../classes/respuestas.class.php");
    //empezamos implementando los siguientes metodos aqui
    /*
    -Función OBTENER API KEY
    -Función OBTENER VOUCHER
    -Función OBTENER MONEDAS
    -Función OBTENER PAÍSES
    -Función OBTENER REGIONES
    -Función OBTENER PLANES
    -Función OBTENER COBERTURAS
    -Función OBTENER PRECIO
    -Función OBTENER LENGUAJES
    -Función OBTENER CATEGORÍA DE PLANES
    -Función OBTENER PRECIO DE LA ORDEN POR FECHA DE NACIMIENTO POR PLAN
    -Función OBTENER PRECIO DE LA ORDEN POR EDAD POR PLAN
    -Función OBTENER PRECIO DE LA ORDEN POR FECHA DE NACIMIENTO
    -Función OBTENER PRECIO DE LA ORDEN POR EDAD
    -Función OBTENER CONDICIONES
    -Función OBTENER UPGRADE
    -Función OBTENER REPORTE DE VENTAS
    -Función OBTENER PAISES - CIUDADES
    -Función OBTENER PAISES - ESTADOS
    -Función OBTENER ASISTENCIA
    -Función OBTENER DETALLE DE ASISTENCIA
    -Función OBTENER LINEA DE TIEMPO
    -Función OBTENGA BENEFICIOS DEL CASO
    -Función OBTENER PAISES - ESTADOS - CIUDADES
    */
?>